// INCLUDE FILE generated by "Pelles C for Windows, version 4.00".

#define DLG_MAIN						1001
#define DLG_ABOUT	                    1002
#define IDM_SIMPLEGRID_DEMO             2001
#define IDM_ABOUT                       2002
#define IDM_EXIT                        2003

#define BMP_SIMPLEGRID_DEMO             4001

#define IDC_SIMPLEGRID1					4003
#define IDC_SIMPLEGRID2					4004
#define IDC_SIMPLEGRID3					4006
#define IDC_SIMPLEGRID4					4007
#define IDC_SIMPLEGRID5					4008
#define ID_LISTMAP					    4009
#define IDC_TAB  						4005
#define IDC_STATIC1                     4006
#define IDC_STATIC2                     4007
#define IDC_STATIC3                     4008

#define IDR_ICO_MAIN					8001
#define IDR_ICO_SMALL					8002
#define IDR_BMP_ON						8003
#define IDR_BMP_OFF 					8004
